version: '3'

services:

  kong-database:
    image: postgres:9.6
    container_name: kong-database
    #user: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
      #- POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      #- "db-data-kong-postgres:/var/lib/postgresql/data"
      - /root/kong_stack/postgres_kong/data:/var/lib/postgresql/data
    network_mode: "bridge"

  kong-migrations:
    image: custom-kong
    container_name: kong-migrations
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations bootstrap -v
    restart: on-failure
    depends_on:
      - kong-database
    links:
      - kong-database:kong-database
    network_mode: "bridge"

  kong:
    image: custom-kong
    container_name: kong
    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_LUA_PACKAGE_PATH=/usr/local/lib/luarocks/rocks-5.1/kong-oidc/1.1.0-0/?.lua;/usr/local/lib/luarocks/rocks-5.1/kong-plugin-jwt-keycloak/1.1.0-0/?.lua;/usr/local/lib/luarocks/rocks-5.1/kong-plugin-header-echo/0.1.0-1/?.lua;./?.lua;./?/init.lua;
      - KONG_PLUGINS=bundled, oidc, jwt-keycloak, kong-plugin-header-echo
      - KONG_LOG_LEVEL=error
    restart: on-failure
    ports:
      - 8002:8000
      - 8022:8002
      - 8445:8445
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8003:8003
      - 8004:8004
    links:
      - kong-database:kong-database
    depends_on:
      - kong-migrations
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - /root/kong_stack/kong.conf.default:/etc/kong/kong.conf
    network_mode: "bridge"
  
  keycloak-database:
    container_name: keycloak-database
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    image: postgres:12
    ports:
      - 5433:5432
    volumes:
      - /root/kong_stack/postgres:/var/lib/postgresql
    network_mode: "bridge"
    
  openldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    ports:
      - 8389:389
    network_mode: "bridge"
  
  konga:
    image: pantsel/konga
    ports:
      - 1337:1337
    links:
      - kong:kong
    container_name: konga
    environment:
      - NODE_ENV=production
    network_mode: "bridge"
    
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    command:
      - "start-dev"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
      - "-Dkeycloak.profile.feature.admin_fine_grained_authz=enabled"
      - "-Dkeycloak.profile.feature.token_exchange=enabled"
      - "-Dkeycloak.profile.feature.declarative_user_profile=enabled"
    depends_on:
      - keycloak-database
      - openldap
    environment:
      - KC_PROXY=edge
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=INFO
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-database
      - DB_PORT=5433
      - DB_USER=keycloak
      - DB_DATABASE=keycloak
      - DB_PASSWORD=password
    ports:
      - 8090:8080
    network_mode: "bridge"
    volumes:
      - /root/kong_stack/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - /root/kong_stack/providers:/opt/keycloak/providers

volumes:
  db-data-kong-postgres: